<?php

/**
 * @file
 * Allows Openstack deployments to be managed through Drupal.
 */

/**
 * Implements hook_libraries_info().
 */
function opencloud_libraries_info() {
  $libraries['php-opencloud'] = array(
    'name' => 'PHP-Opencloud',
    'vendor url' => 'https://github.com/rackspace/php-opencloud',
    'download url' => 'https://github.com/rackspace/php-opencloud/archive/v1.5.7.tar.gz',
    'version' => '1.5.7',
    'path' => 'lib',
    'files' => array(
      'php' => array(
        'OpenCloud/Base/Base.php',
        'OpenCloud/AbstractClass/Service.php',
        'OpenCloud/AbstractClass/Collection.php',
        'OpenCloud/AbstractClass/Nova.php',
        'OpenCloud/AbstractClass/ObjectStore.php',
        'OpenCloud/AbstractClass/PersistentObject.php',
        'OpenCloud/Base/Debug.php',
        'OpenCloud/Base/Exceptions/AsyncError.php',
        'OpenCloud/Base/Exceptions/AsyncHttpError.php',
        'OpenCloud/Base/Exceptions/AsyncTimeoutError.php',
        'OpenCloud/Base/Exceptions/AttributeError.php',
        'OpenCloud/Base/Exceptions/AuthenticationError.php',
        'OpenCloud/Base/Exceptions/CdnError.php',
        'OpenCloud/Base/Exceptions/CdnHttpError.php',
        'OpenCloud/Base/Exceptions/CdnNotAvailableError.php',
        'OpenCloud/Base/Exceptions/CdnTtlError.php',
        'OpenCloud/Base/Exceptions/CollectionError.php',
        'OpenCloud/Base/Exceptions/ContainerCreateError.php',
        'OpenCloud/Base/Exceptions/ContainerDeleteError.php',
        'OpenCloud/Base/Exceptions/ContainerError.php',
        'OpenCloud/Base/Exceptions/ContainerNameError.php',
        'OpenCloud/Base/Exceptions/ContainerNotEmptyError.php',
        'OpenCloud/Base/Exceptions/ContainerNotFoundError.php',
        'OpenCloud/Base/Exceptions/CreateError.php',
        'OpenCloud/Base/Exceptions/CreateUpdateError.php',
        'OpenCloud/Base/Exceptions/CredentialError.php',
        'OpenCloud/Base/Exceptions/DatabaseCreateError.php',
        'OpenCloud/Base/Exceptions/DatabaseDeleteError.php',
        'OpenCloud/Base/Exceptions/DatabaseListError.php',
        'OpenCloud/Base/Exceptions/DatabaseNameError.php',
        'OpenCloud/Base/Exceptions/DatabaseUpdateError.php',
        'OpenCloud/Base/Exceptions/DeleteError.php',
        'OpenCloud/Base/Exceptions/DocumentError.php',
        'OpenCloud/Base/Exceptions/DomainError.php',
        'OpenCloud/Base/Exceptions/EmptyResponseError.php',
        'OpenCloud/Base/Exceptions/EndpointError.php',
        'OpenCloud/Base/Exceptions/FlavorError.php',
        'OpenCloud/Base/Exceptions/HttpError.php',
        'OpenCloud/Base/Exceptions/HttpForbiddenError.php',
        'OpenCloud/Base/Exceptions/HttpOverLimitError.php',
        'OpenCloud/Base/Exceptions/HttpRetryError.php',
        'OpenCloud/Base/Exceptions/HttpTimeoutError.php',
        'OpenCloud/Base/Exceptions/HttpUnauthorizedError.php',
        'OpenCloud/Base/Exceptions/HttpUrlError.php',
        'OpenCloud/Base/Exceptions/IOError.php',
        'OpenCloud/Base/Exceptions/IdRequiredError.php',
        'OpenCloud/Base/Exceptions/ImageError.php',
        'OpenCloud/Base/Exceptions/InstanceCreateError.php',
        'OpenCloud/Base/Exceptions/InstanceDeleteError.php',
        'OpenCloud/Base/Exceptions/InstanceError.php',
        'OpenCloud/Base/Exceptions/InstanceFlavorError.php',
        'OpenCloud/Base/Exceptions/InstanceNotFound.php',
        'OpenCloud/Base/Exceptions/InstanceUpdateError.php',
        'OpenCloud/Base/Exceptions/InvalidArgumentError.php',
        'OpenCloud/Base/Exceptions/InvalidIdTypeError.php',
        'OpenCloud/Base/Exceptions/InvalidIpTypeError.php',
        'OpenCloud/Base/Exceptions/InvalidParameterError.php',
        'OpenCloud/Base/Exceptions/InvalidRequestError.php',
        'OpenCloud/Base/Exceptions/JsonError.php',
        'OpenCloud/Base/Exceptions/MetadataCreateError.php',
        'OpenCloud/Base/Exceptions/MetadataDeleteError.php',
        'OpenCloud/Base/Exceptions/MetadataError.php',
        'OpenCloud/Base/Exceptions/MetadataJsonError.php',
        'OpenCloud/Base/Exceptions/MetadataKeyError.php',
        'OpenCloud/Base/Exceptions/MetadataPrefixError.php',
        'OpenCloud/Base/Exceptions/MetadataUpdateError.php',
        'OpenCloud/Base/Exceptions/MisMatchedChecksumError.php',
        'OpenCloud/Base/Exceptions/MissingValueError.php',
        'OpenCloud/Base/Exceptions/NameError.php',
        'OpenCloud/Base/Exceptions/NetworkCreateError.php',
        'OpenCloud/Base/Exceptions/NetworkDeleteError.php',
        'OpenCloud/Base/Exceptions/NetworkUpdateError.php',
        'OpenCloud/Base/Exceptions/NetworkUrlError.php',
        'OpenCloud/Base/Exceptions/NoContentTypeError.php',
        'OpenCloud/Base/Exceptions/NoNameError.php',
        'OpenCloud/Base/Exceptions/ObjFetchError.php',
        'OpenCloud/Base/Exceptions/ObjectCopyError.php',
        'OpenCloud/Base/Exceptions/ObjectError.php',
        'OpenCloud/Base/Exceptions/RecordTypeError.php',
        'OpenCloud/Base/Exceptions/ServerActionError.php',
        'OpenCloud/Base/Exceptions/ServerCreateError.php',
        'OpenCloud/Base/Exceptions/ServerDeleteError.php',
        'OpenCloud/Base/Exceptions/ServerIpsError.php',
        'OpenCloud/Base/Exceptions/ServerJsonError.php',
        'OpenCloud/Base/Exceptions/ServerUpdateError.php',
        'OpenCloud/Base/Exceptions/ServerUrlError.php',
        'OpenCloud/Base/Exceptions/ServiceValueError.php',
        'OpenCloud/Base/Exceptions/SnapshotError.php',
        'OpenCloud/Base/Exceptions/TempUrlMethodError.php',
        'OpenCloud/Base/Exceptions/UnknownError.php',
        'OpenCloud/Base/Exceptions/UnknownParameterError.php',
        'OpenCloud/Base/Exceptions/UnrecognizedServiceError.php',
        'OpenCloud/Base/Exceptions/UnsupportedExtensionError.php',
        'OpenCloud/Base/Exceptions/UnsupportedFeatureExtension.php',
        'OpenCloud/Base/Exceptions/UnsupportedVersionError.php',
        'OpenCloud/Base/Exceptions/UpdateError.php',
        'OpenCloud/Base/Exceptions/UrlError.php',
        'OpenCloud/Base/Exceptions/UserCreateError.php',
        'OpenCloud/Base/Exceptions/UserDeleteError.php',
        'OpenCloud/Base/Exceptions/UserListError.php',
        'OpenCloud/Base/Exceptions/UserNameError.php',
        'OpenCloud/Base/Exceptions/UserUpdateError.php',
        'OpenCloud/Base/Exceptions/VolumeError.php',
        'OpenCloud/Base/Exceptions/VolueeTypeError.php',
        'OpenCloud/Base/Lang.php',
        'OpenCloud/Base/Metadata.php',
        'OpenCloud/Base/Request/HttpRequestInterface.php',
        'OpenCloud/Base/Request/Curl.php',
        'OpenCloud/Base/Request/Response/Http.php',
        'OpenCloud/Base/Request/Response/Blank.php',
        'OpenCloud/Base/ServiceCatalogItem.php',
        'OpenCloud/Compute/Flavor.php',
        'OpenCloud/Compute/Image.php',
        'OpenCloud/Compute/Network.php',
        'OpenCloud/Compute/Server.php',
        'OpenCloud/Compute/ServerMetadata.php',
        'OpenCloud/Compute/Service.php',
        'OpenCloud/Compute/VolumeAttachment.php',
        'OpenCloud/DNS/AsyncResponse.php',
        'OpenCloud/DNS/Object.php',
        'OpenCloud/DNS/Domain.php',
        'OpenCloud/DNS/Record.php',
        'OpenCloud/DNS/PtrRecord.php',
        'OpenCloud/DNS/Service.php',
        'OpenCloud/DNS/Subdomain.php',
        'OpenCloud/Database/Database.php',
        'OpenCloud/Database/Instance.php',
        'OpenCloud/Database/Service.php',
        'OpenCloud/Database/User.php',
        'OpenCloud/LoadBalancer/Algorithm.php',
        'OpenCloud/LoadBalancer/AllowedDomain.php',
        'OpenCloud/LoadBalancer/LoadBalancer.php',
        'OpenCloud/LoadBalancer/BillableLoadBalancer.php',
        'OpenCloud/LoadBalancer/Protocol.php',
        'OpenCloud/LoadBalancer/Resources/SubResource.php',
        'OpenCloud/LoadBalancer/Resources/Access.php',
        'OpenCloud/LoadBalancer/Resources/ConnectionLogging.php',
        'OpenCloud/LoadBalancer/Resources/ConnectionThrottle.php',
        'OpenCloud/LoadBalancer/Resources/ContentCaching.php',
        'OpenCloud/LoadBalancer/Resources/ErrorPage.php',
        'OpenCloud/LoadBalancer/Resources/HealthMonitor.php',
        'OpenCloud/LoadBalancer/Resources/Metadata.php',
        'OpenCloud/LoadBalancer/Resources/Node.php',
        'OpenCloud/LoadBalancer/Resources/Readonly.php',
        'OpenCloud/LoadBalancer/Resources/NodeEvent.php',
        'OpenCloud/LoadBalancer/Resources/SSLTermination.php',
        'OpenCloud/LoadBalancer/Resources/SessionPersistence.php',
        'OpenCloud/LoadBalancer/Resources/Stats.php',
        'OpenCloud/LoadBalancer/Resources/Usage.php',
        'OpenCloud/LoadBalancer/Resources/VirtualIp.php',
        'OpenCloud/LoadBalancer/Service.php',
        'OpenCloud/ObjectStore/CDNContainer.php',
        'OpenCloud/ObjectStore/Container.php',
        'OpenCloud/ObjectStore/DataObject.php',
        'OpenCloud/ObjectStore/ObjectStoreBase.php',
        'OpenCloud/ObjectStore/ObjectStoreCDN.php',
        'OpenCloud/ObjectStore/Service.php',
        'OpenCloud/Volume/Service.php',
        'OpenCloud/Volume/Snapshot.php',
        'OpenCloud/Volume/Volume.php',
        'OpenCloud/Volume/VolumeType.php',
        'OpenCloud/Globals.php',
        'OpenCloud/OpenStack.php',
        'OpenCloud/Rackspace.php',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_requirements().
 */
function opencloud_requirements() {
  $t = get_t();
  $requirements = array();

  $info = libraries_load('php-opencloud');
  if (!$info['loaded']) {
    $requirements['opencloud'] = array(
      'severity' => REQUIREMENT_ERROR,
      'title' => $t('PHP-Opencloud API'),
      'value' => $t('Failed to load the PHP-Opencloud API'),
      'description' => $t('Please make sure the PHP-Opencloud API library is installed in the libraries directory.'),
    );
  }
  else {
    $requirements['opencloud'] = array(
      'severity' => REQUIREMENT_INFO,
      'title' => $t('PHP-Opencloud API'),
      'value' => $info['version'],
    );
  }

  return $requirements;
}

/**
 * Loads the PHP-Opencloud library.
 */
function opencloud_load_library() {
  if (($library = libraries_detect('php-opencloud')) && !empty($library['installed'])) {
      libraries_load('php-opencloud');
  }
}

/**
 * Generic access control for Opencloud entities.
 *
 * @param string $op
 *   The operation being performed:
 *   - create: The entity is being created.
 *   - view: The entity is being viewed.
 *   - update: The entity is being updated.
 *   - delete: The entity is being deleted.
 * @param obj $entity
 *   (optional) The entity to check access for.
 * @param obj $account
 *   (optional) The account to check access for.
 * @param string $entity_type
 *   The entity type to check access for.
 *
 * @return bool
 *   Whether or not the user can access the entity.
 */
function opencloud_entity_access($op, $entity = NULL, $account = NULL, $entity_type) {
  global $user;
  $account = isset($account) ? $account : $user;

  // Grant access to users with administration access.
  if (user_access('administer ' . $entity_type . ' entities', $account)) {
    return TRUE;
  }

  if ('update' == $op) {
    return user_access('edit ' . $entity_type . ' entities', $account);
  }
  else {
    return user_access("{$op} {$entity_type} entities", $account);
  }
}

/**
 * Generic permissions for Opencloud entity types.
 *
 * @param string $entity_type
 *   The entity type to generate permissions for.
 *
 * @return array
 *   An array with permissions settings for a given entity type.
 */
function opencloud_entity_access_permissions($entity_type) {
  $entity_info = entity_get_info($entity_type);

  $permissions = array();

  // 'administer' permission
  $permissions['administer ' . $entity_type . 'entities'] = array(
    'title' => t('Administer @entity_type', array('@entity_type' => $entity_info['plural label'])),
  );
  // 'create' permission
  $permissions['create ' . $entity_type . 'entities'] = array(
    'title' => t('Create @entity_type', array('@entity_type' => $entity_info['plural label'])),
  );
  // 'view' permission
  $permissions['view ' . $entity_type . 'entities'] = array(
    'title' => t('View @entity_type', array('@entity_type' => $entity_info['plural label'])),
  );
  // 'edit' permission
  $permissions['edit ' . $entity_type . 'entities'] = array(
    'title' => t('Edit @entity_type', array('@entity_type' => $entity_info['plural label'])),
  );
  // 'delete' permission
  $permissions['delete ' . $entity_type . 'entities'] = array(
    'title' => t('Delete @entity_type', array('@entity_type' => $entity_info['plural label'])),
  );

  return $permissions;
}
