<?php

/**
 * @file
 * Allows Openstack deployments to be managed through Drupal.
 */

/**
 * Implements hook_libraries_info().
 */
function opencloud_libraries_info() {
  $libraries['php-opencloud'] = array(
    'name' => 'PHP-Opencloud',
    'vendor url' => 'https://github.com/rackspace/php-opencloud',
    'download url' => 'https://github.com/rackspace/php-opencloud/archive/v1.4.1.tar.gz',
    'path' => 'lib',
    'version' => '1.4.1',
    'files' => array(
      'php' => array(
        'asyncresponse.php',
        'base.php',
        'cloud.php',
        'collection.php',
        'compute.php',
        'container.php',
        'database.php',
        'dataobject.php',
        'dbservice.php',
        'dns.php',
        'exceptions.php',
        'flavor.php',
        'globals.php',
        'http.php',
        'image.php',
        'instance.php',
        'lbresources.php',
        'lbservice.php',
        'loadbalancer.php',
        'metadata.php',
        'network.php',
        'nova.php',
        'objectstore.php',
        'objstorebase.php',
        'openstack.php',
        'persistentobject.php',
        'ptrrecord.php',
        'rackspace.php',
        'record.php',
        'server.php',
        'servermetadata.php',
        'service.php',
        'snapshot.php',
        'user.php',
        'volume.php',
        'volumeattachment.php',
        'volumeservice.inc',
        'volumetype.inc',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_requirements().
 */
function opencloud_requirements() {
  $t = get_t();
  $requirements = array();

  $info = libraries_load('php-opencloud');
  if (!$info['loaded']) {
    $requirements['opencloud'] = array(
      'severity' => REQUIREMENT_ERROR,
      'title' => $t('PHP-Opencloud API'),
      'value' => $t('Failed to load the PHP-Opencloud API'),
      'description' => $t('Please make sure the PHP-Opencloud API library is installed in the libraries directory.'),
    );
  }
  else {
    $requirements['opencloud'] = array(
      'severity' => REQUIREMENT_INFO,
      'title' => $t('PHP-Opencloud API'),
      'value' => $info['version'],
    );
  }

  return $requirements;
}
