<?php

/**
 * @file
 * Defines UI items for Opencloud Provider.
 */


/**
 * Implements hook_menu().
 */
function opencloud_provider_ui_menu() {
  $items = array();

  // Note: admin/opencloud/providers is defined by a default View.

  $items['admin/opencloud/providers/add'] = array(
    'title' => 'Add a new Provider',
    'description' => 'Add a new Openstack-based service provider to access.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('opencloud_provider_ui_settings'),
    'access arguments' => array('access administration pages'),
    'file' => 'includes/opencloud_provider_ui.admin.inc',
  );

  return $items;
}
