<?php

/**
 * @file
 * Allows Openstack providers to be managed through Drupal.
 */

/**
 * Implements hook_entity_info().
 */
function opencloud_provider_entity_info() {
  $entity = array(
    'opencloud_provider' => array(
      'label' => t('Provider'),
      'controller class' => 'OpencloudProviderEntityController',
      'base table' => 'opencloud_provider',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'provider_id',
        'label' => 'name',
      ),
      'view modes' => array(
        'administrator' => array(
          'label' => t('Administrator'),
          'custom settings' => FALSE,
        ),
        'customer' => array(
          'label' => t('Customer'),
          'custom settings' => FALSE,
        ),
      ),
    ),
  );

  return $entity;
}

/**
 * Implements hook_field_extra_fields().
 */
function opencloud_provider_field_extra_fields() {
  $extra = array();

  $extra['opencloud_provider']['opencloud_provider'] = array(
    'form' => array(
      'name' => array(
        'label' => t('Name'),
        'description' => t('The provider name form element.'),
        'weight' => -10,
      ),
      'tenant_id' => array(
        'label' => t('Tenant ID'),
        'description' => t('The tenant ID form element.'),
        'weight' => -5,
      ),
      'username' => array(
        'label' => t('Username'),
        'description' => t('The username form element.'),
        'weight' => 0,
      ),
      'password' => array(
        'label' => t('Password'),
        'description' => t('The password form element.'),
        'weight' => 5,
      ),
    ),
    'display' => array(
      'name' => array(
        'label' => t('Name'),
        'description' => t('The name of this provider.'),
        'weight' => -10,
      ),
      'tenant_id' => array(
        'label' => t('Tenant ID'),
        'description' => t('The tenant ID for this provider.'),
        'weight' => -5,
      ),
      'username' => array(
        'label' => t('Username'),
        'description' => t('The username used for this provider.'),
        'weight' => 0,
      ),
      'password' => array(
        'label' => t('Password'),
        'description' => t('The password or key to use for this provider.',
        'weight' => 5,
      ),
    ),
  );

  return $extra;
}
