<?php

/**
 * @file
 * Defines UI items for Opencloud Provider.
 */


/**
 * Implements hook_menu().
 */
function opencloud_provider_ui_menu() {
  $items = array();

  $items['admin/opencloud/providers'] = array(
    'title' => 'Providers',
    'description' => 'Manage OpenStack-based service providers',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );

  return $items;
}
