<?php

/**
 * @file
 * Provides ability to use Opencloud with the Rackspace Cloud.
 */

/**
 * Implements hook_opencloud_provider_types_alter().
 */
function opencloud_provider_rackspace_opencloud_provider_types_alter(&$types) {
  $types['Rackspace'] = 'Rackspace Cloud';
}

/**
 * Implements hook_opencloud_provider_credentials().
 */
function opencloud_provider_rackspace_opencloud_provider_credentials($provider) {
  if ('Rackspace' == $provider->type) {
    return array(
      'username' => $provider->username,
      'apiKey' => $provider->password,
    );
  }
}

/**
 * Implements hook_opencloud_provider_connection_alter().
 */
function opencloud_provider_rackspace_opencloud_provider_connection_alter(&$connection, $context) {
  $provider = $context['provider'];
  if ('Rackspace' == $provider->type) {
    //$connection->SetDefaults('Compute', 'cloudServersOpenStack', $provider->region);
  }
}
